language: python

python:
  - "2.7"

services:
  - mongodb

before_script:
  - sleep 15
  - mongo test --eval 'db.createUser({user:"evi0s",pwd:"test",roles:["root"]});'

install:
  - pip install -r requirements.txt

script:
  - cd test && pytest --doctest-modules -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls
