language: python

python:
  - "2.7"

services:
  - mongodb

before_script:
  - sleep 5
  - mongo admin --eval 'db.createUser({user:"evi0s",pwd:"test",roles:["root"]});'

install:
  - pip install -r test-requirements.txt

script:
  - cd test && pytest --doctest-modules -v --cov pyqudie --cov-report term-missing

after_success:
  - coveralls --base_dir /home/travis/build/evi0s/pyqudie/
